[build]
  publish = "."

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "DENY"
